/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _SwedishNewYear90ym_h_
#define _SwedishNewYear90ym_h_
//---------------------------------------------------------------------------------
extern const unsigned char SwedishNewYear90ym[];
extern const int SwedishNewYear90ym_size;
//---------------------------------------------------------------------------------
#endif //_SwedishNewYear90ym_h_
//---------------------------------------------------------------------------------
