/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _sphereviolette_h_
#define _sphereviolette_h_
//---------------------------------------------------------------------------------
extern const unsigned char sphereviolette[];
extern const int sphereviolette_size;
//---------------------------------------------------------------------------------
#endif //_sphereviolette_h_
//---------------------------------------------------------------------------------
