;*****************************************************************
;
;	Light Speed Player v1.03
;	Fastest Amiga MOD player ever :)
;	Written By Arnaud Carré (aka Leonard / OXYGENE)
;	https://github.com/arnaud-carre/LSPlayer
;	twitter: @leonard_coder
;
;	"Insane speed" player version ( half scanline average player time! )
;	(this source code is generated by LSPConvert)
;	You can also use the generic LightSpeedPlayer.asm player ( less than 512bytes! )
;
;	MOD in  : 4KiB + 24KiB (4ma.mod)
;	LSP out : 6KiB + 37KiB
;
;	--------How to use--------- 
;
;	bsr LSP_MusicDriver+0 : Init LSP player code
;		a0: LSP music data(any memory)
;		a1: LSP sound bank(chip memory)
;		a2: DMACON 8bits byte address
;
;	bsr LSP_MusicDriver+4 : LSP player tick (call once per frame)
;		a6: should be $dff0a0 (and not $dff000)
;		Used regs: d0/a0/a1/a2/a3/a4
;
;*****************************************************************

	opt o-	; switch off ALL optimizations(we don't want vasm to change some code size, and all optimizations are done!)

LSP_MusicDriver:
			bra.w	.LSP_PlayerInit

;LSP_MusicDriver+4		; Player tick to call each frame
			lea		.LSPVars+8(pc),a1
			move.l	(a1),a0		; byte stream
.process:	moveq	#0,d0
			move.b	(a0)+,d0
			add.w	d0,d0
			move.w	.LSP_JmpTable(pc,d0.w),d0	; 14 cycles
			jmp		.LSP_JmpTable(pc,d0.w)		; 14 cycles

.r_rewind:	move.l	0-8(a1),16-8(a1)
			move.l	24-8(a1),a0
			bra.s	.process


.LSP_JmpTable:		; (131 codes)
			dc.w	-1		; extended code
			dc.w	.r_None-.LSP_JmpTable
			dc.w	.r_Bp-.LSP_JmpTable
			dc.w	.r_BpCv-.LSP_JmpTable
			dc.w	.r_BpDp-.LSP_JmpTable
			dc.w	.r_ApBp-.LSP_JmpTable
			dc.w	.r_Cv-.LSP_JmpTable
			dc.w	.r_Ap-.LSP_JmpTable
			dc.w	.r_Dp-.LSP_JmpTable
			dc.w	.r_BpCvDp-.LSP_JmpTable
			dc.w	.r_ApBpDp-.LSP_JmpTable
			dc.w	.r_Bv-.LSP_JmpTable
			dc.w	.r_ApCvDp-.LSP_JmpTable
			dc.w	.r_ApCv-.LSP_JmpTable
			dc.w	.r_ApBpCv-.LSP_JmpTable
			dc.w	.r_CvpiDpi-.LSP_JmpTable
			dc.w	.r_CrvDr-.LSP_JmpTable
			dc.w	.r_CvpiDvpi-.LSP_JmpTable
			dc.w	.r_ApiCvpiDpi-.LSP_JmpTable
			dc.w	.r_ApBpCvDp-.LSP_JmpTable
			dc.w	.r_ArpBpCrvDr-.LSP_JmpTable
			dc.w	.r_ApDp-.LSP_JmpTable
			dc.w	.r_BpCrvDr-.LSP_JmpTable
			dc.w	.r_ArBrpCrvDr-.LSP_JmpTable
			dc.w	.r_CvDp-.LSP_JmpTable
			dc.w	.r_ArpBp-.LSP_JmpTable
			dc.w	.r_Api-.LSP_JmpTable
			dc.w	.r_ArCrvDr-.LSP_JmpTable
			dc.w	.r_ApCrvDr-.LSP_JmpTable
			dc.w	.r_ApiCvpiDvpi-.LSP_JmpTable
			dc.w	.r_ApBrpCrvDr-.LSP_JmpTable
			dc.w	.r_BrpCrvDr-.LSP_JmpTable
			dc.w	.r_BvCvpiDpi-.LSP_JmpTable
			dc.w	.r_ApBpCrvDr-.LSP_JmpTable
			dc.w	.r_ApBrpCrDr-.LSP_JmpTable
			dc.w	.r_BiCvpiDpi-.LSP_JmpTable
			dc.w	.r_BvCvpiDvpi-.LSP_JmpTable
			dc.w	.r_ApiCviDvpi-.LSP_JmpTable
			dc.w	.r_ApBpCrDr-.LSP_JmpTable
			dc.w	.r_ArpBpCrDr-.LSP_JmpTable
			dc.w	.r_ApiBvCvpiDpi-.LSP_JmpTable
			dc.w	.r_ArBpCrvDr-.LSP_JmpTable
			dc.w	.r_ArBrpCrDr-.LSP_JmpTable
			dc.w	.r_BpiCvpiDpi-.LSP_JmpTable
			dc.w	.r_BviCvpiDvpi-.LSP_JmpTable
			dc.w	.r_Cvpi-.LSP_JmpTable
			dc.w	.r_BviCvpiDpi-.LSP_JmpTable
			dc.w	.r_ApCrv-.LSP_JmpTable
			dc.w	.r_Avp-.LSP_JmpTable
			dc.w	.r_ApCrDr-.LSP_JmpTable
			dc.w	.r_ApiBpiCvpiDvpi-.LSP_JmpTable
			dc.w	.r_ArBpCrDr-.LSP_JmpTable
			dc.w	.r_CviDvpi-.LSP_JmpTable
			dc.w	.r_ApiBviCvpiDvpi-.LSP_JmpTable
			dc.w	.r_BiCviDvpi-.LSP_JmpTable
			dc.w	.r_ArCrDr-.LSP_JmpTable
			dc.w	.r_ApiBiCvpiDpi-.LSP_JmpTable
			dc.w	.r_AiCvpiDpi-.LSP_JmpTable
			dc.w	.r_BrpCrDr-.LSP_JmpTable
			dc.w	.r_ApBrCrvDr-.LSP_JmpTable
			dc.w	.r_BviCviDvpi-.LSP_JmpTable
			dc.w	.r_BrCrvDr-.LSP_JmpTable
			dc.w	.r_ArpCrvDr-.LSP_JmpTable
			dc.w	.r_BvCviDvpi-.LSP_JmpTable
			dc.w	.r_ApiBviCvpiDpi-.LSP_JmpTable
			dc.w	.r_ApiBvpiCvpiDvpi-.LSP_JmpTable
			dc.w	.r_ArpBrpCrvDr-.LSP_JmpTable
			dc.w	.r_BpiCviDvpi-.LSP_JmpTable
			dc.w	.r_ApiBvpiCviDvpi-.LSP_JmpTable
			dc.w	.r_ApiBiCviDvpi-.LSP_JmpTable
			dc.w	.r_BpCrDr-.LSP_JmpTable
			dc.w	.r_CvpiDi-.LSP_JmpTable
			dc.w	.r_ApBrCrDr-.LSP_JmpTable
			dc.w	.r_ApCr-.LSP_JmpTable
			dc.w	.r_BvpiCvpiDvpi-.LSP_JmpTable
			dc.w	.r_Cvi-.LSP_JmpTable
			dc.w	.r_AvpiBpiCvpiDvpi-.LSP_JmpTable
			dc.w	.r_AvpiCvpiDvpi-.LSP_JmpTable
			dc.w	.r_ApCvpiDvpi-.LSP_JmpTable
			dc.w	.r_AiBvCvpiDpi-.LSP_JmpTable
			dc.w	.r_ApiBvCviDvpi-.LSP_JmpTable
			dc.w	.r_CrDr-.LSP_JmpTable
			dc.w	.r_ApiBiCvpiDvpi-.LSP_JmpTable
			dc.w	.r_ArpCrDr-.LSP_JmpTable
			dc.w	.r_BpiCvpiDvpi-.LSP_JmpTable
			dc.w	.r_ApBpiCvpiDpi-.LSP_JmpTable
			dc.w	.r_ApCvpiDi-.LSP_JmpTable
			dc.w	.r_Av-.LSP_JmpTable
			dc.w	.r_AvpiBvpiCviDvpi-.LSP_JmpTable
			dc.w	.r_AvBvCv-.LSP_JmpTable
			dc.w	.r_AvpBviCviDvpi-.LSP_JmpTable
			dc.w	.r_ArBrCrvDr-.LSP_JmpTable
			dc.w	.r_AvpiBiCvpiDpi-.LSP_JmpTable
			dc.w	.r_ApiBvCvpiDvpi-.LSP_JmpTable
			dc.w	.r_ApiCvpiDi-.LSP_JmpTable
			dc.w	.r_AvBv-.LSP_JmpTable
			dc.w	.r_ApBvCvpiDpi-.LSP_JmpTable
			dc.w	.r_ApBvpiCvpiDvpi-.LSP_JmpTable
			dc.w	.r_BvpiCvpiDvi-.LSP_JmpTable
			dc.w	.r_AvpBvi-.LSP_JmpTable
			dc.w	.r_Brp-.LSP_JmpTable
			dc.w	.r_ApCvpiDpi-.LSP_JmpTable
			dc.w	.r_CvpiDvi-.LSP_JmpTable
			dc.w	.r_ApBpiCvpiDvi-.LSP_JmpTable
			dc.w	.r_ArpBrpCrDr-.LSP_JmpTable
			dc.w	.r_AvpiBvpiCvpiDvi-.LSP_JmpTable
			dc.w	.r_AvBvCviDvpi-.LSP_JmpTable
			dc.w	.r_BvpiCviDvpi-.LSP_JmpTable
			dc.w	.r_ApBviCviDvpi-.LSP_JmpTable
			dc.w	.r_AvpBv-.LSP_JmpTable
			dc.w	.r_ApCviDvpi-.LSP_JmpTable
			dc.w	.r_AiCvpiDvpi-.LSP_JmpTable
			dc.w	.r_ArBrCrDr-.LSP_JmpTable
			dc.w	.r_AvBvCvpiDpi-.LSP_JmpTable
			dc.w	.r_AviBvpiCviDvpi-.LSP_JmpTable
			dc.w	.r_ApiBviCviDvpi-.LSP_JmpTable
			dc.w	.r_AvpBiCvpiDpi-.LSP_JmpTable
			dc.w	.r_AvpiCvpiDi-.LSP_JmpTable
			dc.w	.r_ApBiCvpiDpi-.LSP_JmpTable
			dc.w	.r_AvpiBvCvpiDpi-.LSP_JmpTable
			dc.w	.r_AvpiCviDvpi-.LSP_JmpTable
			dc.w	.r_ArpBrCrvDr-.LSP_JmpTable
			dc.w	.r_ArpBrCrv-.LSP_JmpTable
			dc.w	.r_AiCviDvpi-.LSP_JmpTable
			dc.w	.r_AiBvpiCviDvpi-.LSP_JmpTable
			dc.w	.r_AiBiCviDvpi-.LSP_JmpTable
			dc.w	.r_ApiBvpiCviDvi-.LSP_JmpTable
			dc.w	.r_ApiBpiCvpiDi-.LSP_JmpTable
			dc.w	.r_AvpiBviCvpiDvpi-.LSP_JmpTable
			dc.w	.r_ApiBpiCpiDi-.LSP_JmpTable
			dc.w	.r_AvpiBvpiCvpiDvp-.LSP_JmpTable
			dc.w	.r_rewind-.LSP_JmpTable

.LSPVars:	dc.l	0			; 0  word stream loop
			dc.w	0			; 4  reloc has been done
			dc.w	0			; 6  current music BPM
			dc.l	0			; 8  byte stream
			dc.l	0			; 12 m_lfmDmaConPatch
			dc.l	0			; 16 word stream
			dc.l	0			; 20 word stream loop
			dc.l	0			; 24 byte stream loop

; WARNING: in word stream, instrument offset is shifted by -12 bytes (3 last long of .LSPVars)
.LSP_InstrumentInfo:			; (7 instruments)
			dc.w	$0000,$0004,$0141,$0000,$0006,$0040
			dc.w	$0000,$0286,$0101,$0000,$0288,$0040
			dc.w	$0000,$0488,$04a4,$0000,$0488,$0001
			dc.w	$0000,$0dd0,$01b1,$0000,$0dd0,$0001
			dc.w	$0000,$1132,$0114,$0000,$12e2,$0004
			dc.w	$0000,$15dc,$00a5,$0000,$15de,$0004
			dc.w	$0000,$135a,$0141,$0000,$135c,$0010

.resetv:	dc.l	0,0,0,0

; a0: music data (any mem)
; a1: sound bank data (chip mem)
; a2: 8bit DMACON byte address
.LSP_PlayerInit:
			move.l	#$6451ca23,d0
			cmp.l	(a1),d0
			bne.s	.dataError
			cmpi.l	#'LSP1',(a0)+
			bne.s	.dataError
			cmp.l	(a0)+,d0
			bne.s	.dataError
			lea		368(a0),a0		; skip header
			lea		.LSPVars(pc),a3
			move.l	a2,12(a3)
			move.l	a0,16(a3)		; word stream ptr
			movea.l	a0,a4
			add.l	#24390,a4
			move.l	a4,8(a3)		; byte stream ptr

			move.l	a0,(a3)	; word stream loop ptr
			move.l	a4,24(a3)	; byte stream loop ptr
			tst.b	4(a3)
			bne.s	.noReloc
			st		4(a3)
			moveq	#7-1,d0
			lea		.LSP_InstrumentInfo(pc),a0
			move.l	a1,d1
.rloop:		add.l	d1,(a0)
			add.l	d1,6(a0)
			lea		12(a0),a0
			dbf		d0,.rloop
.noReloc:	bset.b	#1,$bfe001	; disable this fucking Low pass filter!!
			lea		.LSPVars+6(pc),a0
			move.w	#125,(a0)		; music BPM
			rts

.dataError:	illegal
; 130 specific callback
.r_None:
		move.l	a0,(a1)+
		rts

.r_Bp:
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		move.l	a0,(a1)
		rts

.r_BpCv:
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		move.l	a0,(a1)
		rts

.r_BpDp:
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$16(a6)
		move.l	a0,(a1)
		rts

.r_ApBp:
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		move.l	a0,(a1)
		rts

.r_Cv:
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		rts

.r_Ap:
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$06(a6)
		move.l	a0,(a1)
		rts

.r_Dp:
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.l	a0,(a1)
		rts

.r_BpCvDp:
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$16(a6)
		move.l	a0,(a1)
		rts

.r_ApBpDp:
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		move.l	a0,(a1)
		rts

.r_Bv:
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		rts

.r_ApCvDp:
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$06(a6)
		move.l	a0,(a1)
		rts

.r_ApCv:
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$06(a6)
		move.l	a0,(a1)
		rts

.r_ApBpCv:
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		move.l	a0,(a1)
		rts

.r_CvpiDpi:
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0c,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$26(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		move.l	a0,(a1)
		rts

.r_CrvDr:
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		lea		.resetv(pc),a3
		move.l	(a3)+,a4
		move.l	(a4)+,$30(a6)
		move.w	(a4)+,$34(a6)
		move.l	(a3)+,a4
		move.l	(a4)+,$20(a6)
		move.w	(a4)+,$24(a6)
		rts

.r_CvpiDvpi:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0c,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$26(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		move.l	a0,(a1)
		rts

.r_ApiCvpiDpi:
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0d,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a3)
		move.l	a0,(a1)
		rts

.r_ApBpCvDp:
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		move.l	a0,(a1)
		rts

.r_ArpBpCrvDr:
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a3
		move.l	(a3)+,a4
		move.l	(a4)+,$30(a6)
		move.w	(a4)+,$34(a6)
		move.l	(a3)+,a4
		move.l	(a4)+,$20(a6)
		move.w	(a4)+,$24(a6)
		move.l	4(a3),a4
		move.l	(a4)+,(a6)
		move.w	(a4)+,$04(a6)
		move.l	a0,(a1)
		rts

.r_ApDp:
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$06(a6)
		move.l	a0,(a1)
		rts

.r_BpCrvDr:
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a3
		move.l	(a3)+,a4
		move.l	(a4)+,$30(a6)
		move.w	(a4)+,$34(a6)
		move.l	(a3)+,a4
		move.l	(a4)+,$20(a6)
		move.w	(a4)+,$24(a6)
		move.l	a0,(a1)
		rts

.r_ArBrpCrvDr:
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a3
		move.l	(a3)+,a4
		move.l	(a4)+,$30(a6)
		move.w	(a4)+,$34(a6)
		move.l	(a3)+,a4
		move.l	(a4)+,$20(a6)
		move.w	(a4)+,$24(a6)
		move.l	(a3)+,a4
		move.l	(a4)+,$10(a6)
		move.w	(a4)+,$14(a6)
		move.l	(a3)+,a4
		move.l	(a4)+,(a6)
		move.w	(a4)+,$04(a6)
		move.l	a0,(a1)
		rts

.r_CvDp:
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.l	a0,(a1)
		rts

.r_ArpBp:
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv+12(pc),a3
		move.l	(a3)+,a4
		move.l	(a4)+,(a6)
		move.w	(a4)+,$04(a6)
		move.l	a0,(a1)
		rts

.r_Api:
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$01,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$06(a6)
		lea		.resetv+12(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a3)+
		move.l	a0,(a1)
		rts

.r_ArCrvDr:
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		lea		.resetv(pc),a3
		move.l	(a3)+,a4
		move.l	(a4)+,$30(a6)
		move.w	(a4)+,$34(a6)
		move.l	(a3)+,a4
		move.l	(a4)+,$20(a6)
		move.w	(a4)+,$24(a6)
		move.l	4(a3),a4
		move.l	(a4)+,(a6)
		move.w	(a4)+,$04(a6)
		rts

.r_ApCrvDr:
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a3
		move.l	(a3)+,a4
		move.l	(a4)+,$30(a6)
		move.w	(a4)+,$34(a6)
		move.l	(a3)+,a4
		move.l	(a4)+,$20(a6)
		move.w	(a4)+,$24(a6)
		move.l	a0,(a1)
		rts

.r_ApiCvpiDvpi:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0d,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a3)
		move.l	a0,(a1)
		rts

.r_ApBrpCrvDr:
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a3
		move.l	(a3)+,a4
		move.l	(a4)+,$30(a6)
		move.w	(a4)+,$34(a6)
		move.l	(a3)+,a4
		move.l	(a4)+,$20(a6)
		move.w	(a4)+,$24(a6)
		move.l	(a3)+,a4
		move.l	(a4)+,$10(a6)
		move.w	(a4)+,$14(a6)
		move.l	a0,(a1)
		rts

.r_BrpCrvDr:
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a3
		move.l	(a3)+,a4
		move.l	(a4)+,$30(a6)
		move.w	(a4)+,$34(a6)
		move.l	(a3)+,a4
		move.l	(a4)+,$20(a6)
		move.w	(a4)+,$24(a6)
		move.l	(a3)+,a4
		move.l	(a4)+,$10(a6)
		move.w	(a4)+,$14(a6)
		move.l	a0,(a1)
		rts

.r_BvCvpiDpi:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0c,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$26(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		move.l	a0,(a1)
		rts

.r_ApBpCrvDr:
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a3
		move.l	(a3)+,a4
		move.l	(a4)+,$30(a6)
		move.w	(a4)+,$34(a6)
		move.l	(a3)+,a4
		move.l	(a4)+,$20(a6)
		move.w	(a4)+,$24(a6)
		move.l	a0,(a1)
		rts

.r_ApBrpCrDr:
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a3
		move.l	(a3)+,a4
		move.l	(a4)+,$30(a6)
		move.w	(a4)+,$34(a6)
		move.l	(a3)+,a4
		move.l	(a4)+,$20(a6)
		move.w	(a4)+,$24(a6)
		move.l	(a3)+,a4
		move.l	(a4)+,$10(a6)
		move.w	(a4)+,$14(a6)
		move.l	a0,(a1)
		rts

.r_BiCvpiDpi:
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0e,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$26(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a3)+
		move.l	a0,(a1)
		rts

.r_BvCvpiDvpi:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0c,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$26(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		move.l	a0,(a1)
		rts

.r_ApiCviDvpi:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0d,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a3)
		move.l	a0,(a1)
		rts

.r_ApBpCrDr:
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a3
		move.l	(a3)+,a4
		move.l	(a4)+,$30(a6)
		move.w	(a4)+,$34(a6)
		move.l	(a3)+,a4
		move.l	(a4)+,$20(a6)
		move.w	(a4)+,$24(a6)
		move.l	a0,(a1)
		rts

.r_ArpBpCrDr:
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a3
		move.l	(a3)+,a4
		move.l	(a4)+,$30(a6)
		move.w	(a4)+,$34(a6)
		move.l	(a3)+,a4
		move.l	(a4)+,$20(a6)
		move.w	(a4)+,$24(a6)
		move.l	4(a3),a4
		move.l	(a4)+,(a6)
		move.w	(a4)+,$04(a6)
		move.l	a0,(a1)
		rts

.r_ApiBvCvpiDpi:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0d,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a3)
		move.l	a0,(a1)
		rts

.r_ArBpCrvDr:
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a3
		move.l	(a3)+,a4
		move.l	(a4)+,$30(a6)
		move.w	(a4)+,$34(a6)
		move.l	(a3)+,a4
		move.l	(a4)+,$20(a6)
		move.w	(a4)+,$24(a6)
		move.l	4(a3),a4
		move.l	(a4)+,(a6)
		move.w	(a4)+,$04(a6)
		move.l	a0,(a1)
		rts

.r_ArBrpCrDr:
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a3
		move.l	(a3)+,a4
		move.l	(a4)+,$30(a6)
		move.w	(a4)+,$34(a6)
		move.l	(a3)+,a4
		move.l	(a4)+,$20(a6)
		move.w	(a4)+,$24(a6)
		move.l	(a3)+,a4
		move.l	(a4)+,$10(a6)
		move.w	(a4)+,$14(a6)
		move.l	(a3)+,a4
		move.l	(a4)+,(a6)
		move.w	(a4)+,$04(a6)
		move.l	a0,(a1)
		rts

.r_BpiCvpiDpi:
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0e,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a3)+
		move.l	a0,(a1)
		rts

.r_BviCvpiDvpi:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0e,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$26(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a3)+
		move.l	a0,(a1)
		rts

.r_Cvpi:
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$04,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		lea		.resetv+4(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		move.l	a0,(a1)
		rts

.r_BviCvpiDpi:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0e,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$26(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a3)+
		move.l	a0,(a1)
		rts

.r_ApCrv:
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$06(a6)
		lea		.resetv+4(pc),a3
		move.l	(a3)+,a4
		move.l	(a4)+,$20(a6)
		move.w	(a4)+,$24(a6)
		move.l	a0,(a1)
		rts

.r_Avp:
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$06(a6)
		move.l	a0,(a1)
		rts

.r_ApCrDr:
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a3
		move.l	(a3)+,a4
		move.l	(a4)+,$30(a6)
		move.w	(a4)+,$34(a6)
		move.l	(a3)+,a4
		move.l	(a4)+,$20(a6)
		move.w	(a4)+,$24(a6)
		move.l	a0,(a1)
		rts

.r_ApiBpiCvpiDvpi:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a3)+
		move.l	a0,(a1)
		rts

.r_ArBpCrDr:
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a3
		move.l	(a3)+,a4
		move.l	(a4)+,$30(a6)
		move.w	(a4)+,$34(a6)
		move.l	(a3)+,a4
		move.l	(a4)+,$20(a6)
		move.w	(a4)+,$24(a6)
		move.l	4(a3),a4
		move.l	(a4)+,(a6)
		move.w	(a4)+,$04(a6)
		move.l	a0,(a1)
		rts

.r_CviDvpi:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0c,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		move.l	a0,(a1)
		rts

.r_ApiBviCvpiDvpi:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a3)+
		move.l	a0,(a1)
		rts

.r_BiCviDvpi:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0e,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a3)+
		move.l	a0,(a1)
		rts

.r_ArCrDr:
		move.l	a0,(a1)+
		lea		.resetv(pc),a3
		move.l	(a3)+,a4
		move.l	(a4)+,$30(a6)
		move.w	(a4)+,$34(a6)
		move.l	(a3)+,a4
		move.l	(a4)+,$20(a6)
		move.w	(a4)+,$24(a6)
		move.l	4(a3),a4
		move.l	(a4)+,(a6)
		move.w	(a4)+,$04(a6)
		rts

.r_ApiBiCvpiDpi:
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a3)+
		move.l	a0,(a1)
		rts

.r_AiCvpiDpi:
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0d,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$26(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a3)
		move.l	a0,(a1)
		rts

.r_BrpCrDr:
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a3
		move.l	(a3)+,a4
		move.l	(a4)+,$30(a6)
		move.w	(a4)+,$34(a6)
		move.l	(a3)+,a4
		move.l	(a4)+,$20(a6)
		move.w	(a4)+,$24(a6)
		move.l	(a3)+,a4
		move.l	(a4)+,$10(a6)
		move.w	(a4)+,$14(a6)
		move.l	a0,(a1)
		rts

.r_ApBrCrvDr:
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a3
		move.l	(a3)+,a4
		move.l	(a4)+,$30(a6)
		move.w	(a4)+,$34(a6)
		move.l	(a3)+,a4
		move.l	(a4)+,$20(a6)
		move.w	(a4)+,$24(a6)
		move.l	(a3)+,a4
		move.l	(a4)+,$10(a6)
		move.w	(a4)+,$14(a6)
		move.l	a0,(a1)
		rts

.r_BviCviDvpi:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0e,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a3)+
		move.l	a0,(a1)
		rts

.r_BrCrvDr:
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		lea		.resetv(pc),a3
		move.l	(a3)+,a4
		move.l	(a4)+,$30(a6)
		move.w	(a4)+,$34(a6)
		move.l	(a3)+,a4
		move.l	(a4)+,$20(a6)
		move.w	(a4)+,$24(a6)
		move.l	(a3)+,a4
		move.l	(a4)+,$10(a6)
		move.w	(a4)+,$14(a6)
		rts

.r_ArpCrvDr:
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a3
		move.l	(a3)+,a4
		move.l	(a4)+,$30(a6)
		move.w	(a4)+,$34(a6)
		move.l	(a3)+,a4
		move.l	(a4)+,$20(a6)
		move.w	(a4)+,$24(a6)
		move.l	4(a3),a4
		move.l	(a4)+,(a6)
		move.w	(a4)+,$04(a6)
		move.l	a0,(a1)
		rts

.r_BvCviDvpi:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0c,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		move.l	a0,(a1)
		rts

.r_ApiBviCvpiDpi:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a3)+
		move.l	a0,(a1)
		rts

.r_ApiBvpiCvpiDvpi:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a3)+
		move.l	a0,(a1)
		rts

.r_ArpBrpCrvDr:
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a3
		move.l	(a3)+,a4
		move.l	(a4)+,$30(a6)
		move.w	(a4)+,$34(a6)
		move.l	(a3)+,a4
		move.l	(a4)+,$20(a6)
		move.w	(a4)+,$24(a6)
		move.l	(a3)+,a4
		move.l	(a4)+,$10(a6)
		move.w	(a4)+,$14(a6)
		move.l	(a3)+,a4
		move.l	(a4)+,(a6)
		move.w	(a4)+,$04(a6)
		move.l	a0,(a1)
		rts

.r_BpiCviDvpi:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0e,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a3)+
		move.l	a0,(a1)
		rts

.r_ApiBvpiCviDvpi:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a3)+
		move.l	a0,(a1)
		rts

.r_ApiBiCviDvpi:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a3)+
		move.l	a0,(a1)
		rts

.r_BpCrDr:
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a3
		move.l	(a3)+,a4
		move.l	(a4)+,$30(a6)
		move.w	(a4)+,$34(a6)
		move.l	(a3)+,a4
		move.l	(a4)+,$20(a6)
		move.w	(a4)+,$24(a6)
		move.l	a0,(a1)
		rts

.r_CvpiDi:
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0c,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		move.l	a0,(a1)
		rts

.r_ApBrCrDr:
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a3
		move.l	(a3)+,a4
		move.l	(a4)+,$30(a6)
		move.w	(a4)+,$34(a6)
		move.l	(a3)+,a4
		move.l	(a4)+,$20(a6)
		move.w	(a4)+,$24(a6)
		move.l	(a3)+,a4
		move.l	(a4)+,$10(a6)
		move.w	(a4)+,$14(a6)
		move.l	a0,(a1)
		rts

.r_ApCr:
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$06(a6)
		lea		.resetv+4(pc),a3
		move.l	(a3)+,a4
		move.l	(a4)+,$20(a6)
		move.w	(a4)+,$24(a6)
		move.l	a0,(a1)
		rts

.r_BvpiCvpiDvpi:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0e,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a3)+
		move.l	a0,(a1)
		rts

.r_Cvi:
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$04,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv+4(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		move.l	a0,(a1)
		rts

.r_AvpiBpiCvpiDvpi:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a3)+
		move.l	a0,(a1)
		rts

.r_AvpiCvpiDvpi:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0d,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a3)
		move.l	a0,(a1)
		rts

.r_ApCvpiDvpi:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0c,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		move.l	a0,(a1)
		rts

.r_AiBvCvpiDpi:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0d,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$26(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a3)
		move.l	a0,(a1)
		rts

.r_ApiBvCviDvpi:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0d,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a3)
		move.l	a0,(a1)
		rts

.r_CrDr:
		move.l	a0,(a1)+
		lea		.resetv(pc),a3
		move.l	(a3)+,a4
		move.l	(a4)+,$30(a6)
		move.w	(a4)+,$34(a6)
		move.l	(a3)+,a4
		move.l	(a4)+,$20(a6)
		move.w	(a4)+,$24(a6)
		rts

.r_ApiBiCvpiDvpi:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a3)+
		move.l	a0,(a1)
		rts

.r_ArpCrDr:
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a3
		move.l	(a3)+,a4
		move.l	(a4)+,$30(a6)
		move.w	(a4)+,$34(a6)
		move.l	(a3)+,a4
		move.l	(a4)+,$20(a6)
		move.w	(a4)+,$24(a6)
		move.l	4(a3),a4
		move.l	(a4)+,(a6)
		move.w	(a4)+,$04(a6)
		move.l	a0,(a1)
		rts

.r_BpiCvpiDvpi:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0e,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a3)+
		move.l	a0,(a1)
		rts

.r_ApBpiCvpiDpi:
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0e,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a3)+
		move.l	a0,(a1)
		rts

.r_ApCvpiDi:
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0c,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		move.l	a0,(a1)
		rts

.r_Av:
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		rts

.r_AvpiBvpiCviDvpi:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a3)+
		move.l	a0,(a1)
		rts

.r_AvBvCv:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		rts

.r_AvpBviCviDvpi:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0e,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a3)+
		move.l	a0,(a1)
		rts

.r_ArBrCrvDr:
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		lea		.resetv(pc),a3
		move.l	(a3)+,a4
		move.l	(a4)+,$30(a6)
		move.w	(a4)+,$34(a6)
		move.l	(a3)+,a4
		move.l	(a4)+,$20(a6)
		move.w	(a4)+,$24(a6)
		move.l	(a3)+,a4
		move.l	(a4)+,$10(a6)
		move.w	(a4)+,$14(a6)
		move.l	(a3)+,a4
		move.l	(a4)+,(a6)
		move.w	(a4)+,$04(a6)
		rts

.r_AvpiBiCvpiDpi:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a3)+
		move.l	a0,(a1)
		rts

.r_ApiBvCvpiDvpi:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0d,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a3)
		move.l	a0,(a1)
		rts

.r_ApiCvpiDi:
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0d,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a3)
		move.l	a0,(a1)
		rts

.r_AvBv:
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		rts

.r_ApBvCvpiDpi:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0c,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		move.l	a0,(a1)
		rts

.r_ApBvpiCvpiDvpi:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0e,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a3)+
		move.l	a0,(a1)
		rts

.r_BvpiCvpiDvi:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0e,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a3)+
		move.l	a0,(a1)
		rts

.r_AvpBvi:
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$02,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$06(a6)
		lea		.resetv+8(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a3)+
		move.l	a0,(a1)
		rts

.r_Brp:
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		lea		.resetv+8(pc),a3
		move.l	(a3)+,a4
		move.l	(a4)+,$10(a6)
		move.w	(a4)+,$14(a6)
		move.l	a0,(a1)
		rts

.r_ApCvpiDpi:
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0c,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		move.l	a0,(a1)
		rts

.r_CvpiDvi:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0c,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		move.l	a0,(a1)
		rts

.r_ApBpiCvpiDvi:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0e,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a3)+
		move.l	a0,(a1)
		rts

.r_ArpBrpCrDr:
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a3
		move.l	(a3)+,a4
		move.l	(a4)+,$30(a6)
		move.w	(a4)+,$34(a6)
		move.l	(a3)+,a4
		move.l	(a4)+,$20(a6)
		move.w	(a4)+,$24(a6)
		move.l	(a3)+,a4
		move.l	(a4)+,$10(a6)
		move.w	(a4)+,$14(a6)
		move.l	(a3)+,a4
		move.l	(a4)+,(a6)
		move.w	(a4)+,$04(a6)
		move.l	a0,(a1)
		rts

.r_AvpiBvpiCvpiDvi:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a3)+
		move.l	a0,(a1)
		rts

.r_AvBvCviDvpi:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0c,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		move.l	a0,(a1)
		rts

.r_BvpiCviDvpi:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0e,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a3)+
		move.l	a0,(a1)
		rts

.r_ApBviCviDvpi:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0e,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a3)+
		move.l	a0,(a1)
		rts

.r_AvpBv:
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$06(a6)
		move.l	a0,(a1)
		rts

.r_ApCviDvpi:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0c,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		move.l	a0,(a1)
		rts

.r_AiCvpiDvpi:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0d,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$26(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a3)
		move.l	a0,(a1)
		rts

.r_ArBrCrDr:
		move.l	a0,(a1)+
		lea		.resetv(pc),a3
		move.l	(a3)+,a4
		move.l	(a4)+,$30(a6)
		move.w	(a4)+,$34(a6)
		move.l	(a3)+,a4
		move.l	(a4)+,$20(a6)
		move.w	(a4)+,$24(a6)
		move.l	(a3)+,a4
		move.l	(a4)+,$10(a6)
		move.w	(a4)+,$14(a6)
		move.l	(a3)+,a4
		move.l	(a4)+,(a6)
		move.w	(a4)+,$04(a6)
		rts

.r_AvBvCvpiDpi:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0c,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$26(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		move.l	a0,(a1)
		rts

.r_AviBvpiCviDvpi:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a3)+
		move.l	a0,(a1)
		rts

.r_ApiBviCviDvpi:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a3)+
		move.l	a0,(a1)
		rts

.r_AvpBiCvpiDpi:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0e,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a3)+
		move.l	a0,(a1)
		rts

.r_AvpiCvpiDi:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0d,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a3)
		move.l	a0,(a1)
		rts

.r_ApBiCvpiDpi:
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0e,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a3)+
		move.l	a0,(a1)
		rts

.r_AvpiBvCvpiDpi:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0d,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a3)
		move.l	a0,(a1)
		rts

.r_AvpiCviDvpi:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0d,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a3)
		move.l	a0,(a1)
		rts

.r_ArpBrCrvDr:
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a3
		move.l	(a3)+,a4
		move.l	(a4)+,$30(a6)
		move.w	(a4)+,$34(a6)
		move.l	(a3)+,a4
		move.l	(a4)+,$20(a6)
		move.w	(a4)+,$24(a6)
		move.l	(a3)+,a4
		move.l	(a4)+,$10(a6)
		move.w	(a4)+,$14(a6)
		move.l	(a3)+,a4
		move.l	(a4)+,(a6)
		move.w	(a4)+,$04(a6)
		move.l	a0,(a1)
		rts

.r_ArpBrCrv:
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$06(a6)
		lea		.resetv+4(pc),a3
		move.l	(a3)+,a4
		move.l	(a4)+,$20(a6)
		move.w	(a4)+,$24(a6)
		move.l	(a3)+,a4
		move.l	(a4)+,$10(a6)
		move.w	(a4)+,$14(a6)
		move.l	(a3)+,a4
		move.l	(a4)+,(a6)
		move.w	(a4)+,$04(a6)
		move.l	a0,(a1)
		rts

.r_AiCviDvpi:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0d,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a3)
		move.l	a0,(a1)
		rts

.r_AiBvpiCviDvpi:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a3)+
		move.l	a0,(a1)
		rts

.r_AiBiCviDvpi:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a3)+
		move.l	a0,(a1)
		rts

.r_ApiBvpiCviDvi:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a3)+
		move.l	a0,(a1)
		rts

.r_ApiBpiCvpiDi:
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a3)+
		move.l	a0,(a1)
		rts

.r_AvpiBviCvpiDvpi:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a3)+
		move.l	a0,(a1)
		rts

.r_ApiBpiCpiDi:
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a3)+
		move.l	a0,(a1)
		rts

.r_AvpiBvpiCvpiDvp:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$07,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv+4(pc),a3
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a3)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a3)+
		move.l	a0,(a1)
		rts

